name: Manual Execute All Notebooks
on:
  workflow_dispatch:

jobs:
  ExecuteNotebooks:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_scheduled.yml@0ea14fcf22bfa36f86d7a9500003bf6454e6f2e5  # main
   with:
      python-version: ${{ vars.PYTHON_VERSION }}
