name: Manual Full Archive Execute-Store-Generate HTML
on:
  workflow_dispatch:

jobs:
  GenerateHTML:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_build_merge_manual.yml@0ea14fcf22bfa36f86d7a9500003bf6454e6f2e5  # main
   with:
      python-version: ${{ vars.PYTHON_VERSION }}
