name: Manual Security Scan
on:
  workflow_dispatch:
  
jobs:
  Bandit:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_security_scan.yml@0ea14fcf22bfa36f86d7a9500003bf6454e6f2e5  # main
